language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.3'

before_script:
    - composer self-update
    - composer install --prefer-source
    - composer require php-coveralls/php-coveralls

script:
    - vendor/bin/phpcs
    - vendor/bin/psalm
    - vendor/bin/phpunit --coverage-clover clover.xml

after_success:
    - vendor/bin/php-coveralls -v
