name: CI

on: push

jobs:
    test:
        name: Test

        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.0']

        runs-on: ubuntu-18.04

        steps:
            # Setup
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: pcov
                    tools: cs2pr
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Cache Dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache
                    key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: php${{ matrix.php-version }}-composer-
            -   name: Install Dependencies
                run: composer install --no-interaction --no-ansi --no-suggest

            # Test
            -   name: Codestyle
                run: php vendor/bin/phpcs -q --report=checkstyle | cs2pr
            -   name: Psalm
                run: php vendor/bin/psalm --output-format=github --shepherd
            -   name: PHPUnit Checks Matcher
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            -   name: Unit Tests
                run: php vendor/bin/phpunit --coverage-clover=coverage.xml

            -   name: Coverage Report
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
